### ISSUE TITLE
monix-grpc with Armeria does not work with streaming APIs

### ISSUE THREAD

**Issue by mushtaq** [monix/monix-grpc#43]
You can reproduce the issue by cloning [this repo](https://github.com/mushtaq/armeria-grpc-monix).

Task based apis work fine, e.g.:

`sbt 'testOnly -- *get-reply*'`

```
top.HelloServiceTest:
+ get-reply: gproto 0.654s
```

But Observable based apis throw an error, e.g.:

`sbt 'testOnly -- *lots-of-replies*'`

```
WARN  c.l.a.server.HttpResponseSubscriber - [id: 0x949b072b, L:/127.0.0.1:59750 - R:/127.0.0.1:59752] Unexpected exception from a service or a response publisher: InitialDispatcherService{router=CachingRouter{delegate=com.linecorp.armeria.server.Routers$SequentialRouter@1b1435b2, findCache=com.linecorp.armeria.internal.shaded.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache@1a2b2b3d, findAllCache=com.linecorp.armeria.internal.shaded.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache@24674b39}, delegate=UnframedGrpcService(com.linecorp.armeria.server.grpc.FramedGrpcService@326eed33)}
io.grpc.StatusException: CANCELLED
```

<details>
  <summary>Stack Trace</summary>

```txt
	at io.grpc.Status.asException(Status.java:543)
	at com.linecorp.armeria.server.grpc.AbstractServerCall.closeListener(AbstractServerCall.java:295)
	at com.linecorp.armeria.server.grpc.AbstractServerCall.doClose(AbstractServerCall.java:236)
	at com.linecorp.armeria.server.grpc.AbstractServerCall.close(AbstractServerCall.java:219)
	at com.linecorp.armeria.server.grpc.AbstractServerCall.close(AbstractServerCall.java:214)
	at com.linecorp.armeria.server.grpc.FramedGrpcService.lambda$startCall$4(FramedGrpcService.java:322)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:152)
	at com.linecorp.armeria.internal.common.CancellationScheduler$CancellationFuture.doComplete(CancellationScheduler.java:520)
	at com.linecorp.armeria.internal.common.CancellationScheduler.invokeTask(CancellationScheduler.java:476)
	at com.linecorp.armeria.internal.common.CancellationScheduler.finishNow0(CancellationScheduler.java:322)
	at com.linecorp.armeria.internal.common.CancellationScheduler.finishNow(CancellationScheduler.java:306)
	at com.linecorp.armeria.internal.server.DefaultServiceRequestContext.cancel(DefaultServiceRequestContext.java:327)
	at com.linecorp.armeria.server.AggregatingDecodedHttpRequest.abortResponse(AggregatingDecodedHttpRequest.java:180)
	at com.linecorp.armeria.server.Http2RequestDecoder.onRstStreamRead(Http2RequestDecoder.java:356)
	at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onRstStreamRead(Http2FrameListenerDecorator.java:59)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDecoder.java:442)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onRstStreamRead(Http2InboundFrameLogger.java:80)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:509)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:259)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
	at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.linecorp.armeria.common.stream.ClosedStreamException: received a RST_STREAM frame: PROTOCOL_ERROR
top.HelloServiceTest:
==> X top.HelloServiceTest.lots-of-replies: gproto  0.719s io.grpc.StatusRuntimeException: CANCELLED
at io.grpc.Status.asRuntimeException(Status.java:535)
at monix.grpc.runtime.client.ClientCallListeners$CallStatus.toException(ClientCallListeners.scala:19)
at monix.grpc.runtime.client.ClientCallListeners$StreamingClientCallListener.onClose(ClientCallListeners.scala:96)
at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.close(ArmeriaClientCall.java:499)
at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.transportReportStatus(ArmeriaClientCall.java:443)
at com.linecorp.armeria.internal.common.grpc.HttpStreamDeframer.processOnError(HttpStreamDeframer.java:136)
at com.linecorp.armeria.internal.common.stream.DecodedStreamMessage$DecodingSubscriber.onError(DecodedStreamMessage.java:274)
at com.linecorp.armeria.common.stream.CancellableStreamMessage$CloseEvent.notifySubscriber(CancellableStreamMessage.java:269)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:300)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:292)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:429)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:372)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:328)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:314)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.tryClose(DefaultStreamMessage.java:458)
at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:447)
at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:331)
at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:373)
at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:319)
at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:314)
at com.linecorp.armeria.client.Http2ResponseDecoder.onStreamClosed(Http2ResponseDecoder.java:144)
at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357)
at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1007)
at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:963)
at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515)
at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:521)
at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:628)
at io.netty.handler.codec.http2.Http2ConnectionHandler.processRstStreamWriteResult(Http2ConnectionHandler.java:909)
at io.netty.handler.codec.http2.Http2ConnectionHandler.access$1100(Http2ConnectionHandler.java:66)
at io.netty.handler.codec.http2.Http2ConnectionHandler$4.operationComplete(Http2ConnectionHandler.java:824)
at io.netty.handler.codec.http2.Http2ConnectionHandler$4.operationComplete(Http2ConnectionHandler.java:821)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:717)
at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:272)
at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352)
at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:421)
at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
at io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:204)
at io.netty.handler.flush.FlushConsolidationHandler.flushIfNeeded(FlushConsolidationHandler.java:197)
at io.netty.handler.flush.FlushConsolidationHandler.resetReadAndFlushIfNeeded(FlushConsolidationHandler.java:192)
at io.netty.handler.flush.FlushConsolidationHandler.channelReadComplete(FlushConsolidationHandler.java:145)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1415)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:171)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:829)
at toListL @ top.HelloServiceTest.$init$$$anonfun$4$$anonfun$1(HelloServiceTest.scala:68)
at toListL @ top.HelloServiceTest.$init$$$anonfun$4$$anonfun$1(HelloServiceTest.scala:68)
3422 [armeria-common-worker-nio-2-3] WARN  c.l.a.server.logging.LoggingService - [sreqId=40763cec, chanId=949b072b, raddr=127.0.0.1:59752, laddr=127.0.0.1:59750][h2c://mushtaq/example.armeria.grpc.scala.HelloService/LotsOfReplies#POST] Request: {startTime=2022-10-03T13:07:59.885Z(1664802479885690), length=14B, duration=38041µs(38041666ns), scheme=gproto+h2c, name=LotsOfReplies, headers=[:method=POST, :path=/example.armeria.grpc.scala.HelloService/LotsOfReplies, :scheme=http, :authority=127.0.0.1:59750, content-type=application/grpc+proto, te=trailers, grpc-accept-encoding=gzip, grpc-timeout=15000000u, user-agent=armeria/1.19.0, content-length=14], content=DefaultRpcRequest{serviceType=GrpcLogUtil, serviceName=example.armeria.grpc.scala.HelloService, method=LotsOfReplies, params=[HelloRequest(Armeria,UnknownFieldSet(Map()))]}}
3423 [armeria-common-worker-nio-2-3] WARN  c.l.a.server.logging.LoggingService - [sreqId=40763cec, chanId=949b072b, raddr=127.0.0.1:59752, laddr=127.0.0.1:59750][h2c://mushtaq/example.armeria.grpc.scala.HelloService/LotsOfReplies#POST] Response: {startTime=2022-10-03T13:07:59.926Z(1664802479926018), length=56B, duration=33549µs(33549598ns), totalDuration=73878µs(73878578ns), cause=io.grpc.StatusException: CANCELLED, headers=[:status=200, :method=POST, :path=/example.armeria.grpc.scala.HelloService/LotsOfReplies, :scheme=http, :authority=127.0.0.1:59750, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-encoding=gzip, content-type=application/grpc+proto, te=trailers, grpc-accept-encoding=gzip, grpc-timeout=15000000u, user-agent=armeria/1.19.0, content-length=14], content=CompletableRpcResponse{cause=io.grpc.StatusException: CANCELLED}}
io.grpc.StatusException: CANCELLED
at io.grpc.Status.asException(Status.java:543)
at com.linecorp.armeria.internal.common.grpc.GrpcLogUtil.rpcResponse(GrpcLogUtil.java:61)
at com.linecorp.armeria.server.grpc.AbstractServerCall.closeListener(AbstractServerCall.java:268)
at com.linecorp.armeria.server.grpc.AbstractServerCall.doClose(AbstractServerCall.java:236)
at com.linecorp.armeria.server.grpc.AbstractServerCall.close(AbstractServerCall.java:219)
at com.linecorp.armeria.server.grpc.AbstractServerCall.close(AbstractServerCall.java:214)
at com.linecorp.armeria.server.grpc.FramedGrpcService.lambda$startCall$4(FramedGrpcService.java:322)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:152)
at com.linecorp.armeria.internal.common.CancellationScheduler$CancellationFuture.doComplete(CancellationScheduler.java:520)
at com.linecorp.armeria.internal.common.CancellationScheduler.invokeTask(CancellationScheduler.java:476)
at com.linecorp.armeria.internal.common.CancellationScheduler.finishNow0(CancellationScheduler.java:322)
at com.linecorp.armeria.internal.common.CancellationScheduler.finishNow(CancellationScheduler.java:306)
at com.linecorp.armeria.internal.server.DefaultServiceRequestContext.cancel(DefaultServiceRequestContext.java:327)
at com.linecorp.armeria.server.AggregatingDecodedHttpRequest.abortResponse(AggregatingDecodedHttpRequest.java:180)
at com.linecorp.armeria.server.Http2RequestDecoder.onRstStreamRead(Http2RequestDecoder.java:356)
at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onRstStreamRead(Http2FrameListenerDecorator.java:59)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDecoder.java:442)
at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onRstStreamRead(Http2InboundFrameLogger.java:80)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:509)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:259)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.linecorp.armeria.common.stream.ClosedStreamException: received a RST_STREAM frame: PROTOCOL_ERROR
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	top.HelloServiceTest
```

</details>

Will appreciate help in figuring out the underlying issue. Ping @jvican @borissmidt

**Comment by ikhoon** [comment]
I debugged the issue and I realized that Monix-gRPC sends a wrong content-length header for streaming responses.
`content-length: 14` is not the correct value for the response.
![image](https://user-images.githubusercontent.com/1866157/193762303-fcac30e2-8d53-4480-95cb-6d705f0f5838.png)
If it is a streaming response, a response does not need a content-length.
So you can remove the `content-length` as a workaround.
```scala
Server.builder()
      .decorator((delegate, ctx, req) => {
        delegate
          .serve(ctx, req)
          .mapHeaders(headers =>
            headers.toBuilder.removeAndThen(HttpHeaderNames.CONTENT_LENGTH).build()
          )
      })
```
I will also add a defense code to Armeria's server-side gRPC runtime to remove a content-length specified in the response `Metadata`.
https://github.com/line/armeria/blob/c69ef83fb45d8d6521597583ebe86069a12f3f48/grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java#L437

Also replied to the question in the Armeria Slack: https://line-armeria.slack.com/archives/C1NGPBUH2/p1664868331079439?thread_ts=1664854849.131239&cid=C1NGPBUH2

**Comment by ikhoon** [comment]
I'm not 100% sure but the request content-length seems to be reused for the response content-length.
```
logging.traffic.client.http2 - [id: 0x94c582c9, L:/127.0.0.1:55442 - R:127.0.0.1/127.0.0.1:55440] OUTBOUND HEADERS: streamId=3 headers=DefaultHttp2Headers[:method: POST, :path: /example.armeria.grpc.scala.HelloService/LotsOfReplies, :scheme: http, :authority: 127.0.0.1:55440, content-type: application/grpc+proto, te: trailers, grpc-accept-encoding: gzip, grpc-timeout: 15000000u, content-length: 14, user-agent: armeria/1.19.0] padding=0 endStream=false
logging.traffic.client.http2 - [id: 0x94c582c9, L:/127.0.0.1:55442 - R:127.0.0.1/127.0.0.1:55440] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=14 bytes=00000000090a0741726d65726961
logging.traffic.server.http2 - [id: 0xd4374f4d, L:/127.0.0.1:55440 - R:/127.0.0.1:55442] INBOUND HEADERS: streamId=3 headers=[:method=POST, :path=/example.armeria.grpc.scala.HelloService/LotsOfReplies, :scheme=http, :authority=127.0.0.1:55440, content-type=application/grpc+proto, te=trailers, grpc-accept-encoding=gzip, grpc-timeout=15000000u, content-length=14, user-agent=armeria/1.19.0] padding=0 endStream=false
logging.traffic.server.http2 - [id: 0xd4374f4d, L:/127.0.0.1:55440 - R:/127.0.0.1:55442] INBOUND DATA: streamId=3 padding=0 endStream=true length=14 bytes=00000000090a0741726d65726961
ERROR: transport error 202: send failed: Broken pipe
logging.traffic.client.http2 - [id: 0x94c582c9, L:/127.0.0.1:55442 - R:127.0.0.1/127.0.0.1:55440] OUTBOUND RST_STREAM: streamId=3 errorCode=8
.client.logging.LoggingClient - [creqId=61c487e0, chanId=94c582c9, laddr=127.0.0.1:55442, raddr=127.0.0.1:55440][http://127.0.0.1:55440/example.armeria.grpc.scala.HelloService/LotsOfReplies#POST] Request: {startTime=2022-10-04T07:22:40.382Z(1664868160382279), length=14B, duration=3431ms(3431594666ns), scheme=gproto+h2c, name=LotsOfReplies, headers=[:method=POST, :path=/example.armeria.grpc.scala.HelloService/LotsOfReplies, :scheme=http, :authority=127.0.0.1:55440, content-type=application/grpc+proto, te=trailers, grpc-accept-encoding=gzip, grpc-timeout=15000000u, content-length=14], content=DefaultRpcRequest{serviceType=GrpcLogUtil, serviceName=example.armeria.grpc.scala.HelloService, method=LotsOfReplies, params=[HelloRequest(Armeria,UnknownFieldSet(Map()))]}}
```

**Comment by ikhoon** [comment]
Double checked the response metadata which contains all information of the request headers.
